name = "aragorn2"
version = "0.0.2"
description = "Secure password hashing, powered by Argon2"
licenses = ["MIT"]
repository = { type = "github", user = "maxdeviant", repo = "aragorn2" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
startest = ">= 0.2.4 and < 1.0.0"
