[package]
name = "argonaut_ffi"
version = "0.1.0"
publish = false
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
argon2 = "0.5.3"
rand_core = { version = "0.6.4", features = ["std"] }
rustler = "0.32.1"
